### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing'

### ISSUE THREAD

**Issue by Imgkl** [thisisjsimon/SiteSniffer#7]
Whenever I try to run a simple script, I encounter this problem

```
❯ python3.10 /Users/Gokul/Desktop/ssl_auto_update.py
Traceback (most recent call last):
  File "/Users/Gokul/Desktop/ssl_auto_update.py", line 1, in <module>
    from sitesniffer import SiteSniffe
  File "/opt/homebrew/lib/python3.10/site-packages/sitesniffer/__init__.py", line 18, in <module>
    from ._sitesniffer import SiteSniffer
  File "/opt/homebrew/lib/python3.10/site-packages/sitesniffer/_sitesniffer.py", line 10, in <module>
    from typing import Any, Literal, Optional, Self
ImportError: cannot import name 'Self' from 'typing' (/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py)
```

**Comment by Imgkl** [comment]
I did try `pip3 install typing-extensions --upgrade`, but still facing the issue

**Comment by realshouzy** [comment]
You need to install Python 3.11 or higher. Self is a new typing feature.

**Comment by thisisjsimon** [comment]
The issue has been resolved after adding the python_requires option in the setup.py file. Now, it requires a version of Python 3.11 or higher to run the package.
